In [1]:
import numpy as np

In [4]:
np.random.random()

0.3660367902111894

In [8]:
#seed helps in getting same random values
np.random.seed(1)

np.random.random()

0.417022004702574

In [12]:
#within range
np.random.uniform(3, 10)

4.027291235719791

In [15]:
np.random.uniform(1, 100, 10).reshape(5, 2)

array([[89.56605969,  9.41937693],
       [ 4.86642354, 17.81321154],
       [87.93610784, 10.73633655],
       [42.68965488, 95.83106348],
       [53.78336321, 69.49583428]])

In [18]:
np.random.randint(1, 10, 5) #of size 5

array([1, 4, 3, 1, 5])

In [19]:
a = np.random.randint(1, 10, 6)
a

array([3, 8, 8, 9, 7, 4])

In [20]:
np.max(a)

9

In [22]:
a[np.argmax(a)]

9

In [23]:
a = np.random.randint(1, 10, 6)
a

array([8, 8, 5, 6, 4, 7])

In [24]:
a[a%2 == 1] = -1

In [25]:
a

array([ 8,  8, -1,  6,  4, -1])

In [29]:
a = np.random.randint(1, 50, 6)
a

array([ 3, 13, 28, 22, 12,  8])

In [30]:
np.where(a%2 ==1, -1, a)

array([-1, -1, 28, 22, 12,  8])

In [31]:
a

array([ 3, 13, 28, 22, 12,  8])