In [1]:

import numpy as np

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [6]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
arr6 = np.arange(5, 16, 2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [18]:
arr7 = np.linspace(10, 20, 10)

arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [20]:
arr8 = arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [21]:
##properties and attr
arr1.shape

(5,)

In [22]:
arr2.shape

(2, 3)

In [32]:
arr9 = np.array([[[1,2,67],[3,4,78],[11,12,87]],[[5,6,89], [7,8,89],[13,14,100]]])

arr9

array([[[  1,   2,  67],
        [  3,   4,  78],
        [ 11,  12,  87]],

       [[  5,   6,  89],
        [  7,   8,  89],
        [ 13,  14, 100]]])

In [33]:
arr9.shape

(2, 3, 3)

In [34]:
arr9.ndim

3

In [35]:
arr2.ndim

2

In [36]:
arr1.ndim

1

In [37]:
arr1.size

5

In [39]:
arr9.size

18

In [40]:
arr9.itemsize

4

In [41]:
arr8.itemsize

8

In [42]:
arr8.dtype

dtype('float64')

In [44]:
arr9.dtype

dtype('int32')

In [45]:
arr9.astype('float')

array([[[  1.,   2.,  67.],
        [  3.,   4.,  78.],
        [ 11.,  12.,  87.]],

       [[  5.,   6.,  89.],
        [  7.,   8.,  89.],
        [ 13.,  14., 100.]]])