In [2]:

import numpy as np

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
arr6 = np.arange(5, 16, 2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [10]:
arr7 = np.linspace(10, 20, 10)

arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [11]:
arr8 = arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [12]:
##properties and attr
arr1.shape

(5,)

In [13]:
arr2.shape

(2, 3)

In [14]:
arr9 = np.array([[[1,2,67],[3,4,78],[11,12,87]],[[5,6,89], [7,8,89],[13,14,100]]])

arr9

array([[[  1,   2,  67],
        [  3,   4,  78],
        [ 11,  12,  87]],

       [[  5,   6,  89],
        [  7,   8,  89],
        [ 13,  14, 100]]])

In [15]:
arr9.shape

(2, 3, 3)

In [16]:
arr9.ndim

3

In [17]:
arr2.ndim

2

In [18]:
arr1.ndim

1

In [19]:
arr1.size

5

In [20]:
arr9.size

18

In [21]:
arr9.itemsize

4

In [22]:
arr8.itemsize

8

In [23]:
arr8.dtype

dtype('float64')

In [24]:
arr9.dtype

dtype('int32')

In [25]:
arr9.astype('float')

array([[[  1.,   2.,  67.],
        [  3.,   4.,  78.],
        [ 11.,  12.,  87.]],

       [[  5.,   6.,  89.],
        [  7.,   8.,  89.],
        [ 13.,  14., 100.]]])

In [26]:
lista = range(100)
arr11 = np.arange(100)

In [27]:
import sys

In [28]:
print(sys.getsizeof(87)*len(lista))

2800


In [29]:
print(arr11.itemsize*arr11.size)

400


In [33]:
##Indexing slicing and iterations

arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [34]:
arr1

array([1, 2, 3, 4, 5])

In [36]:
arr1[3]

4

In [38]:
arr1[2:4]

array([3, 4])

In [39]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
arr12[2] #row

array([ 8,  9, 10, 11])

In [46]:
arr12[:,1:3] #slicing

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [47]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [48]:
arr12[4:6,2:4] #slicing

array([[18, 19],
       [22, 23]])

In [49]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [51]:
for i in arr12:
    print (i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [52]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [55]:
##Numpy operation

arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)

In [56]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [57]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [58]:
arr4.max()

11

In [59]:
arr4.min(axis=0)

array([6, 7])

In [60]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [61]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [64]:
#fancy indexing

arr4.ndim

2

In [66]:
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [67]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [68]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [69]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [71]:
arr5 = np.arange(12,18).reshape(2,3)
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [72]:
np.hstack((arr3,arr5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [73]:
np.vstack((arr3,arr5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [74]:
np.hsplit(arr3,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [75]:
np.vsplit(arr3,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [76]:
arr8 = np.arange(24).reshape(6,4)

In [77]:
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [78]:
#discontinious ones

arr8[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])